name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Project
      run: dotnet build ./src/VoiceTrigger/VoiceTrigger.csproj
    - name: Get dotnet-version
      run: dotnet tool install -g dotnet-version-cli
    - name: Version em
      run: dotnet version -f ./src/VoiceTrigger/VoiceTrigger.csproj patch --output-format=json
    
